# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import poll.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_choice_choice_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_picture',
        ),
        migrations.AddField(
            model_name='ballot',
            name='choice_picture',
            field=models.ImageField(blank=True, null=True, upload_to=poll.models.get_image_path),
        ),
    ]
